#!/bin/sh

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

php ./run_it.php

