#!/bin/bash

ruby script/generate model ProvXn sessionid:string operator:string uid:string dn:string employeenumber:string userpassword:string userclass:string givenname:string

ruby script/generate scaffold ProvXn sessionid:string operator:string uid:string dn:string employeenumber:string userpassword:string userclass:string givenname:string

