development:
  perform-authentication: true
  username: gregf
  password: password
  allowed-hosts: 10.20.24.26, 10.10.25.32, 198.242.56.41, 64.35.176.34

test:
  perform-authentication: true
  username: gregf
  password: password
  allowed-hosts: 10.10.24.95, 10.10.25.32

production:
  perform-authentication: true
  username: gregf
  password: password
  allowed-hosts: 10.10.24.95, 10.10.24.25
